# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "버전과 빌드 번호 증가 (TestFlight 배포용)"
  lane :bump_version do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      workspace: "ToMyongJi.xcworkspace",
      scheme: "ToMyongJi-iOS"
    )
  end

  # desc "테스트 실행 (모듈별로 추가 가능)"
  # lane :test do
  #   run_tests(
  #     workspace: "ToMyongJi.xcworkspace",
  #     scheme: "ToMyongJi-iOS",
  #     device: "iPhone 15 Pro"
  #   )
  # end

  desc "Sync certificates and provisioning profiles"
  lane :sync_certificates do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "./AuthKey.p8",
      duration: 1200,
      in_house: false
    )
    
    match(
      type: "appstore",
      app_identifier: "com.tomyongji.ios",
      api_key: api_key
    )
  end

  desc "Deploy a new version to TestFlight"
  lane :beta do
    sync_certificates
    increment_build_number
    build_ios_app(
      workspace: "ToMyongJi.xcworkspace",
      scheme: "ToMyongJi-iOS",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy a new version to App Store"
  lane :release do
    sync_certificates
    increment_build_number
    build_ios_app(
      workspace: "ToMyongJi.xcworkspace",
      scheme: "ToMyongJi-iOS",
      export_method: "app-store"
    )
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true
    )
  end
end
