name: build-tomyongji-ios-app

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  beta:
    name: testflight deploy
    runs-on: macos-14
    if: github.event.pull_request.merged == true && !startsWith(github.event.head_commit.message, '[fastlane]')
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Install Tuist CLI
        run: bash <(curl -Ls https://install.tuist.io)

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          
      - name: Setup Match
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: |
          bundle exec fastlane match appstore --readonly

      - name: Tuist Generate
        run: tuist generate

      - name: Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_STORE_CONNECT_API_KEY_ID: "8L63PR5VMY"
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: "1938b5bc-4d44-4546-8960-204d5b167b20"
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        run: bundle exec fastlane ios beta

  # release:
  #   name: app store deploy
  #   runs-on: macos-14
  #   if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true && !startsWith(github.event.head_commit.message, '[fastlane]')
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: jdx/mise-action@v2
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.2.3'
  #         bundler-cache: true

  #     - name: Setup Xcode Version
  #       uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: '16.2.0'

  #     - name: Install Tuist CLI
  #       run: bash <(curl -Ls https://install.tuist.io)

  #     - name: Install Dependencies
  #       run: |
  #         gem install bundler
  #         bundle install

  #     - name: Setup Match
  #       env:
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #         MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  #       run: |
  #         bundle exec fastlane match appstore --readonly

  #     - name: Tuist Generate
  #       run: tuist generate

  #     - name: Deploy to App Store
  #       env:
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #         MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #         MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  #         APP_STORE_CONNECT_API_KEY_ID: "8L63PR5VMY"
  #         APP_STORE_CONNECT_API_KEY_ISSUER_ID: "1938b5bc-4d44-4546-8960-204d5b167b20"
  #         APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  #         FASTLANE_HIDE_TIMESTAMP: true
  #         FASTLANE_SKIP_UPDATE_CHECK: true
  #       run: bundle exec fastlane ios release
