name: build-tomyongji-ios-app

on:
  push:
    branches:
      - feature/**
      - fix
      - hotfix
  pull_request:
    branches:
      - main
      - develop

jobs:
  beta:
    name: testflight deploy
    runs-on: macos-14
    strategy:
      matrix:
        xcodebuild-scheme: ['App']
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Install Tuist CLI
        run: bash <(curl -Ls https://install.tuist.io)

      - name: Install FastLane
        run: brew install fastlane

      - name: Tuist Clean Command
        run: tuist clean

      - name: Tuist Fetch Command
        run: tuist fetch

      - name: Tuist Generate Command
        run: tuist generate

      - name: Deploy to TestFlight
        if: github.event.pull_request.base.ref == 'develop' && github.event.action == 'closed' && github.event.pull_request.merged == true && !startsWith(github.event.head_commit.message, '[fastlane]')
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          FASTLANE_HIDE_TIMESTAMP: true
          FASTLANE_SKIP_UPDATE_CHECK: true
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        run: bundle exec fastlane ios beta

  # release:
  #   name: app store deploy
  #   runs-on: macos-14
  #   strategy:
  #     matrix:
  #       xcodebuild-scheme: ['App']
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: jdx/mise-action@v2
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.2.3'
  #         bundler-cache: true

  #     - name: Setup Xcode Version
  #       uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: '16.2.0'

  #     - name: Install Tuist CLI
  #       run: bash <(curl -Ls https://install.tuist.io)

  #     - name: Install FastLane
  #       run: brew install fastlane

  #     - name: Tuist Clean Command
  #       run: tuist clean

  #     - name: Tuist Fetch Command
  #       run: tuist fetch

  #     - name: Tuist Generate Command
  #       run: tuist generate

  #     - name: Deploy to App Store
  #       if: github.event.pull_request.base.ref == 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true && !startsWith(github.event.head_commit.message, '[fastlane]')
  #       env:
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #         APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
  #         APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  #         APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
  #         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #         FASTLANE_HIDE_TIMESTAMP: true
  #         FASTLANE_SKIP_UPDATE_CHECK: true
  #         MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #         MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  #       run: bundle exec fastlane ios release
