name: iOS CI/CD

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  beta:
    name: Deploy to TestFlight
    if: github.ref == 'refs/heads/develop'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Install tuist
        run: brew install tuist
      - name: Tuist Generate
        run: tuist generate
      - name: Install dependencies
        run: |
          bundle install
          bundle exec pod install
      - name: Create AuthKey.p8
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}" > ./AuthKey.p8
      - name: Deploy to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        run: bundle exec fastlane beta

  release:
    name: Deploy to App Store
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Install tuist
        run: brew install tuist
      - name: Tuist Generate
        run: tuist generate
      - name: Install dependencies
        run: |
          bundle install
          bundle exec pod install
      - name: Create AuthKey.p8
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}" > ./AuthKey.p8
      - name: Deploy to App Store
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        run: bundle exec fastlane release
