name: build-tomyongji-ios-app

on:
  push:
    branches:
      - feature/**
      - fix
      - hotfix
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  beta:
    name: testflight deploy
    runs-on: macos-14
    strategy:
      matrix:
        xcodebuild-scheme: ['App']
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Install Tuist CLI
        run: bash <(curl -Ls https://install.tuist.io)

      - name: Install FastLane
        run: brew install fastlane

      - name: Copy App Store Connect API Key
        run: |
          cp fastlane/AuthKey_8L63PR5VMY.p8 .

      - name: Tuist Generate
        run: tuist generate

      - name: Deploy to TestFlight
        if: github.event.pull_request.merged == true && !startsWith(github.event.head_commit.message, '[fastlane]')
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: "8L63PR5VMY"
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: "1938b5bc-4d44-4546-8960-204d5b167b20"
        run: bundle exec fastlane ios beta

  # release:
  #   name: app store deploy
  #   runs-on: macos-14
  #   strategy:
  #     matrix:
  #       xcodebuild-scheme: ['App']
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: jdx/mise-action@v2
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.2.3'
  #         bundler-cache: true

  #     - name: Setup Xcode Version
  #       uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: '16.2.0'

  #     - name: Install Tuist CLI
  #       run: bash <(curl -Ls https://install.tuist.io)

  #     - name: Install FastLane
  #       run: brew install fastlane

  #     - name: Setup SSH
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.MATCH_SSH_KEY }}" > ~/.ssh/id_ed25519
  #         chmod 600 ~/.ssh/id_ed25519
  #         ssh-keyscan github.com >> ~/.ssh/known_hosts

  #     - name: Tuist Clean Command
  #       run: tuist clean

  #     - name: Tuist Fetch Command
  #       run: tuist fetch

  #     - name: Tuist Generate Command
  #       run: tuist generate

  #     - name: Deploy to App Store
  #       if: github.event.pull_request.base.ref == 'main' && github.event.action == 'closed' && github.event.pull_request.merged == true && !startsWith(github.event.head_commit.message, '[fastlane]')
  #       env:
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #         APP_STORE_CONNECT_API_KEY_ID: "8L63PR5VMY"
  #         APP_STORE_CONNECT_API_KEY_ISSUER_ID: "1938b5bc-4d44-4546-8960-204d5b167b20"
  #         KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #         FASTLANE_HIDE_TIMESTAMP: true
  #         FASTLANE_SKIP_UPDATE_CHECK: true
  #         MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  #       run: bundle exec fastlane ios release
